appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
hiera.yaml:
  delete: true
data/common.yaml:
  delete: true
CHANGELOG.md:
  delete: true
.travis.yml:
  branches:
    - '---main'
    - master
  extras:
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
      stage: spec
Gemfile:
  required:
    ':development':
        - gem: rubocop-performance
          condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.5.0')"