appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
hiera.yaml:
  delete: true
data/common.yaml:
  delete: true
CHANGELOG.md:
  delete: true
.travis.yml:
  branches:
    - '---main'
    - master
  extras:
    -
      env: PUPPET_GEM_VERSION="~> 4.0" CHECK=parallel_spec
      rvm: 2.1.9
      stage: spec
Gemfile:
  required:
    ':development':
        # Install rubocop-perfomance
        - gem: rubocop-performance
          condition: "Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.5.0')"
        # Install puppet-module-posix-* according ruby version
        - gem: puppet-module-posix-dev-r#{minor_version}
          version: ~> 0.5
          condition:  Gem::Requirement.create('~> 2.1.0').satisfied_by?(Gem::Version.new(RUBY_VERSION.dup))
          platforms:
          - ruby
        - gem: puppet-module-posix-default-r#{minor_version}
          version: ~> 0.5
          condition:  Gem::Requirement.create('~> 2.1.0').satisfied_by?(Gem::Version.new(RUBY_VERSION.dup))
          platforms:
          - ruby
    ':system_tests':
        - gem: puppet-module-posix-system-r#{minor_version}
          version: ~> 0.5
          condition:  Gem::Requirement.create('~> 2.1.0').satisfied_by?(Gem::Version.new(RUBY_VERSION.dup))
          platforms:
          - ruby